Fix display-driver build on GCC 12
Recent versions of nixos-unstable have moved from GCC 9 to 12, which
breaks to build. Flag -mno-outline-atomics is needed for the kernel
module, to avoid errors sucs as:

ERROR: modpost: "__aarch64_cas4_sync" [nvidia.ko] undefined!
ERROR: modpost: "__aarch64_ldadd8_sync" [nvidia.ko] undefined!
ERROR: modpost: "__aarch64_ldadd4_sync" [nvidia.ko] undefined!
ERROR: modpost: "__aarch64_cas8_sync" [nvidia.ko] undefined!

This change has been backported from jetson_35.3.1

Signed-off-by: Mika Tammi <mika.tammi@unikie.com>